name: jvmhs
version: '0.2.0'
author: Christian Gram Kalhauge
maintainer: "Christian Gram Kalhauge <chrg@dtu.dk>"
synopsis: A library for reading Java class-files
license: BSD3
license-file: LICENSE
category: Language, Java, JVM
github: ucla-pls/jvmhs

description: |
  A library to sematically read a class from a file.

ghc-options: 
- -Wall
# - -Wcompat
# - -Wincomplete-record-updates
# - -Wincomplete-uni-patterns
# - -Wredundant-constraints

extra-source-files:
  - LICENSE
  - package.yaml
  - README.md
  - test/stdlib-stubs.json
  - test/data/classes/*.class

dependencies:
  - base >= 4.10 && < 4.18
  - jvm-binary >= 0.6.0 && < 0.12.0
  - aeson 
  - attoparsec
  - autodocodec
  - binary
  - bytestring
  - cassava
  - containers
  - deepseq
  - directory
  - fgl
  - fgl-visualize
  - filepath
  - hashable
  - lens
  - lens-action
  - mtl
  - primitive
  - process
  - text
  - transformers
  - unordered-containers
  - vector
  - zip-archive
  - template-haskell

library:
  source-dirs: src

tests:
  jvmhs-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - jvmhs
      - hspec
      - tasty
      - QuickCheck
      - filepath
      - directory
      - text
      - generic-random
      - hspec-discover
      - hspec-expectations-pretty-diff
      - autodocodec-yaml
      - autodocodec-schema
      - generic-random
      - typed-process
      - HUnit >= 1.6.0.0 
      - nicify-lib >= 1.0.1
