resolver: lts-11.19
packages:
- jvmhs
- javaq
- jreduce
- location:
    git: git@bitbucket.org:ucla-pls/reduce.git
    commit: f6c332a219be3c91817d17d72ee76cec61d760c9 
  extra-dep: true
- location:
    git: git@github.com:ucla-pls/jvm-binary.git
    commit: 5e0be595fc40c7f37680d401d0836647cc0060e8 
  extra-dep: true
extra-deps: 
  - fgl-visualize-0.1.0.1
  - dotgen-0.4.2
  - mtl-2.2.2
flags: {}
extra-package-dbs:
build:
  library-profiling: true
  executable-profiling: true
