resolver: lts-12.11
packages:
- jvmhs
- javaq
- jreduce
- location: 
    git: https://github.com/ucla-pls/reduce.git
    commit: 350b7220e4c00c6717155266ffc90a09739d403f
    subdirs:
      - reduce
      - reduce-util
  extra-dep: true
- location:
    git: https://github.com/ucla-pls/jvm-binary.git
    commit: 059dce79b204cee348995d506f7a93c16e5e4d11
  extra-dep: true
extra-deps: 
  - fgl-visualize-0.1.0.1
  - dotgen-0.4.2
  - mtl-2.2.2
    #  - jvm-binary-0.2.0
flags: {}
extra-package-dbs:
build:
  library-profiling: true
  executable-profiling: true
