resolver: lts-11.19
packages:
- jvmhs
- javaq
- jreduce
- location:
    git: git@bitbucket.org:ucla-pls/reduce.git
    commit: d74c8853aee45e86f0dc7e1113f2cc47a4ec23c4 
  extra-dep: true
- location:
    git: git@github.com:ucla-pls/jvm-binary.git
    commit: a21fdf3b8ed9c23f5b287747683b0fe24fc0d277 
  extra-dep: true
extra-deps: 
  - fgl-visualize-0.1.0.1
  - dotgen-0.4.2
  - mtl-2.2.2
flags: {}
extra-package-dbs:
build:
  library-profiling: true
  executable-profiling: true
