resolver: lts-12.26
packages:
- jvmhs
- javaq
# - location: 
#     git: https://github.com/ucla-pls/jvm-binary.git
#     commit: 7646cace06b10c88ca4d237ea646b0e4cdb6591e 
#   extra-dep: true
extra-deps: 
  - fgl-visualize-0.1.0.1
  - dotgen-0.4.2
  - jvm-binary-0.5.0
flags: {}
extra-package-dbs:
build:
  library-profiling: true
  executable-profiling: true
