resolver: lts-12.24
packages:
- jvmhs
- javaq
- jreduce
- location: 
    git: https://github.com/ucla-pls/reduce.git
    commit: 471a89c5174a4410a613c0768eb8760ca8343af8
    subdirs:
      - reduce
      - reduce-util
  extra-dep: true
- location: 
    git: https://github.com/ucla-pls/jvm-binary.git
    commit: e55478b1a663196a85c8328ed5374b44a4f1d629
  extra-dep: true
extra-deps: 
  - fgl-visualize-0.1.0.1
  - dotgen-0.4.2
  - mtl-2.2.2
    # - jvm-binary-0.3.0
flags: {}
extra-package-dbs:
build:
  library-profiling: true
  executable-profiling: true
