resolver: lts-12.11
packages:
- jvmhs
- javaq
- jreduce
- location:
    git: git@bitbucket.org:ucla-pls/reduce.git
    commit: d74c8853aee45e86f0dc7e1113f2cc47a4ec23c4 
  extra-dep: true
extra-deps: 
  - fgl-visualize-0.1.0.1
  - dotgen-0.4.2
  - mtl-2.2.2
  - jvm-binary-0.2.0
flags: {}
extra-package-dbs:
build:
  library-profiling: true
  executable-profiling: true
