resolver: lts-10.5
packages:
- jvmhs
- javaq
- jreduce
extra-deps: 
  - fgl-visualize-0.1.0.1
  - dotgen-0.4.2
  - mtl-2.2.2
  - jvm-binary-0.1.0
flags: {}
extra-package-dbs:
build:
  library-profiling: true
  executable-profiling: true
