name: jvmhs
version: '0.0.1'
author: Christian Gram Kalhauge
maintainer: Christian Gram Kalhauge <kalhauge@cs.ucla.edu>
synopsis: A library for reading Java class-files

license: MIT
license-file: LICENSE
category: Language, Java, JVM
github: ucla-pls/jvmhs

description: |
  A library to sematically read a class from a file.

ghc-options: -Wall

extra-source-files:
  - LICENSE
  - package.yaml
  - README.md

dependencies:
  - base >= 4.10 && < 4.11
  - jvm-binary >= 0.1.0 && < 0.2.0
  - lens
  - aeson
  - lens-action
  - zip-archive
  - bytestring
  - directory
  - filepath
  - process
  - containers
  - text
  - mtl
  - deepseq
  - fgl
  - fgl-visualize

library:
  source-dirs: src

tests:
  jvmhs-test:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - jvmhs
      - tasty
      - tasty-hunit
