name: jvmhs
version: '0.0.1'
author: Christian Gram Kalhauge
maintainer: Christian Gram Kalhauge <kalhauge@cs.ucla.edu>
synopsis: A library for reading Java class-files

license: BSD3
license-file: LICENSE
category: Language, Java, JVM
github: ucla-pls/jvmhs

description: |
  A library to sematically read a class from a file.

ghc-options: 
 - -Wall
 - -Wcompat
 - -Wincomplete-record-updates
 - -Wincomplete-uni-patterns
 - -Wredundant-constraints

extra-source-files:
  - LICENSE
  - package.yaml
  - README.md

dependencies:
  - base >= 4.10 && < 4.12
  - jvm-binary >= 0.6.0 && < 0.8.0
  - lens
  - aeson
  - lens-action
  - zip-archive
  - bytestring
  - directory
  - filepath
  - process
  - containers
  - text
  - vector
  - mtl
  - transformers
  - deepseq
  - unordered-containers
  - hashable
  - fgl
  - fgl-visualize
  - attoparsec

library:
  source-dirs: src

tests:
  jvmhs-test:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - jvmhs
      - hspec
      - tasty
      - QuickCheck
      - filepath
      - directory
      - text
      - generic-random
      - hspec-discover
      - hspec-expectations-pretty-diff
