name: jreduce
description: |
  A tool for reducing Java Bytecode files 
version: 0.0.1
author: Christian Gram Kalhauge
maintainer: Christian Gram Kalhauge <kalhauge@cs.ucla.edu>
synopsis: A tool for reducing Java Bytecode files 

license: MIT
license-file: ../LICENSE
category: Language, Java, JVM
github: ucla-pls/jvmhs

dependencies:
  - base >= 4.10 && < 4.12
  - reduce
  - docopt
  - lens
  - lens-action
  - aeson
  - containers
  - filepath
  - bytestring
  - text
  - jvmhs
  - process
  - directory
  - temporary
  - vector
  - split
  - time
  - mtl
  - random
  - transformers
  - cassava
  - unordered-containers

default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

ghc-options:
  - -threaded

executables:
  jreduce:
    source-dirs: .
    main: Main.hs
