name: jreduce
description: |
  A tool for reducing Java Bytecode files 
version: 0.0.1
author: Christian Gram Kalhauge
maintainer: Christian Gram Kalhauge <kalhauge@cs.ucla.edu>
synopsis: A tool for reducing Java Bytecode files 

license: MIT
license-file: LICENSE
category: Language, Java, JVM
github: ucla-pls/jvmhs

dependencies:
  - base >= 4.10 && < 4.13
  - reduce
  - reduce-util
  - jvmhs
  - optparse-applicative
  - mtl
  - unordered-containers
  - lens
  - lens-action
  - filepath
  - unliftio
  - zip-archive
  - bytestring
  - deepseq
  - containers
  - text
  - cassava

library:
  source-dirs: src

executables:
  jreduce:
    source-dirs: .
    main: Main.hs
    dependencies: 
      - jreduce
    ghc-options:
      - -O2
      - -threaded
